services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      secrets:
        - transit_config
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=development
      - DEBUG=true
    command: ["npm", "run", "start"]
    secrets:
      - source: transit_config
        target: /app/transit-config.json
    stdin_open: true
    tty: true

secrets:
  transit_config:
    file: ./transit-config.json
