services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      secrets:
        - transit_config
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=development
      - DEBUG=true
    command: ["npm", "run", "start"]
    volumes:
      - type: bind
        source: ./transit-config.json
        target: /app/transit-config.json
        read_only: true
        bind:
          selinux: Z
    stdin_open: true
    tty: true

secrets:
  transit_config:
    file: ./transit-config.json
