services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        NEXT_PUBLIC_GA_MEASUREMENT_ID: ${NEXT_PUBLIC_GA_MEASUREMENT_ID}
        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
        NEXT_PUBLIC_KOFI_TIER_PAGE_URL: ${NEXT_PUBLIC_KOFI_TIER_PAGE_URL}
        NEXT_PUBLIC_ADMIN_PUBKE: ${NEXT_PUBLIC_ADMIN_PUBKEY}
        NEXT_PUBLIC_MODERATORS: ${NEXT_PUBLIC_MODERATORS}
        NEXT_PUBLIC_NOSTR_RELAYS: ${NEXT_PUBLIC_NOSTR_RELAYS}
        NEXT_PUBLIC_BUS_STOP_DISCUSSION_ID: ${NEXT_PUBLIC_BUS_STOP_DISCUSSION_ID}
        NEXT_PUBLIC_DISCUSSIONS_ENABLED: ${NEXT_PUBLIC_DISCUSSIONS_ENABLED}
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    command: ["npm", "run", "start"]
    networks:
      - app-network

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    restart: unless-stopped
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  temp-data:
    driver: local
